name: Local Config
version: 1.0.0
schema: v1
models:
  # Auto Complete
  - name: Granite4.1 8B [Q6]
    provider: lmstudio
    model: granite-4.1-8b@q6_k_xl
    roles:
      - autocomplete
    apiBase: https://llm.deviltea.me/v1/
    apiKey: ${{ secrets.LM_STUDIO_API_KEY }}
    requestOptions:
      headers:
        Cf-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
        Cf-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
  - name: Granite4.1 8B [Q5]
    provider: lmstudio
    model: granite-4.1-8b@q5_k_xl
    roles:
      - autocomplete
    apiBase: https://llm.deviltea.me/v1/
    apiKey: ${{ secrets.LM_STUDIO_API_KEY }}
    requestOptions:
      headers:
        Cf-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
        Cf-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
  - name: Codegemma 7B [Q6]
    provider: lmstudio
    model: codegemma-7b@q6_k
    roles:
      - autocomplete
    apiBase: https://llm.deviltea.me/v1/
    apiKey: ${{ secrets.LM_STUDIO_API_KEY }}
    requestOptions:
      headers:
        Cf-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
        Cf-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
  - name: Codegemma 7B [Q5]
    provider: lmstudio
    model: codegemma-7b@q5_k_xl
    roles:
      - autocomplete
    apiBase: https://llm.deviltea.me/v1/
    apiKey: ${{ secrets.LM_STUDIO_API_KEY }}
    requestOptions:
      headers:
        Cf-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
        Cf-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}

  # Chat
  - name: Qwen3.6 [128K] [35B A3B] [Q6 K]
    provider: lmstudio
    model: qwen3.6-35b-a3b-uncensored-heretic-native-mtp-preserved@q6_k
    apiBase: https://llm.deviltea.me/v1/
    apiKey: ${{ secrets.LM_STUDIO_API_KEY }}
    requestOptions:
      headers:
        Cf-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
        Cf-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
  - name: Qwen3.6 [128K] [35B A3B] [Q5 K M]
    provider: lmstudio
    model: qwen3.6-35b-a3b-uncensored-heretic-native-mtp-preserved@q5_k_m
    apiBase: https://llm.deviltea.me/v1/
    apiKey: ${{ secrets.LM_STUDIO_API_KEY }}
    requestOptions:
      headers:
        Cf-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
        Cf-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
  - name: Qwen3.6 [128K] [35B A3B] [APEX I BALANCED]
    provider: lmstudio
    model: mudler/qwen3.6-35b-a3b-uncensored-heretic-apex-gguf/qwen3.6-35b-a3b-uncensored-heretic-apex-i-balanced.gguf
    apiBase: https://llm.deviltea.me/v1/
    apiKey: ${{ secrets.LM_STUDIO_API_KEY }}
    requestOptions:
      headers:
        Cf-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
        Cf-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}